# -*- coding: utf-8 -*-
"""Bitcamp2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1e1CELoIEYdG7OH3G6qgdkC-4f6QWMx
"""

!sudo apt install tesseract-ocr
!pip install pytesseract

pip install faker

from PIL import Image, ImageDraw, ImageFont
from faker import Faker
import random
import os

# Setup
faker = Faker()
output_dir = "typed_prescriptions_input"
os.makedirs(output_dir, exist_ok=True)

# Sample data
medications = [
    "Paracetamol 500mg", "Amoxicillin 250mg", "Lisinopril 10mg", "Abecma", "Abilify", "Abilify Asimtufii", "Abilify Maintena", "Abiraterone", "Acetaminophen", "Acetazolamide",
    "Acetylcysteine", "Actemra", "Acyclovir", "Adalimumab", "Adderall", "Adderall XR", "Advair Diskus", "Advil", "Afinitor", "Agamree", "Aimovig", "Ajovy", "Albuterol", "Aldactone",
    "Alecensa", "Alendronate", "Alfuzosin", "Allegra", "Allopurinol", "Alprazolam", "Alprolix", "Alunbrig", "Amantadine", "Ambien", "Ambroxol", "Amiodarone", "Amitriptyline",
    "Amlodipine", "Amoxicillin", "Amoxicillin and Clavulanate", "Amphetamine and dextroamphetamine", "Ampicillin", "Amvuttra", "Anastrozole", "AndroGel", "Annovera", "Apalutamide",
    "Apixaban", "Apokyn", "Apriso", "Aptiom", "Arikayce", "Arimidex", "Aripiprazole", "Aristada", "Aromasin", "Ascorbic acid", "Aspirin", "Atarax", "Atenolol", "Ativan",
    "Atogepant", "Atomoxetine", "Atorvastatin", "Aubagio", "Augmentin", "Austedo", "Auvelity", "Auvi-Q", "avacincaptad pegol", "Avonex", "Avsola", "Azathioprine", "Azelastine",
    "Azilect", "Azithromycin", "Azulfidine", "A/B Otic", "Abacavir", "Abacavir and lamivudine", "Abacavir and Lamivudine Tablets", "Abacavir Oral Solution", "Abacavir Sulfate",
    "Abacavir Sulfate Tablets", "Abacavir, dolutegravir, and lamivudine", "Abacavir, Lamivudine and Zidovudine Tablets", "Abacavir, lamivudine, and zidovudine", "Abaloparatide",
    "Abametapir", "Abatacept", "Abatuss DMX", "Abavite", "Abbokinase", "Abciximab", "Abecma", "Abelcet", "Abemaciclib", "Abilify", "Abilify (Aripiprazole Intramuscular)",
    "Abilify Asimtufii", "Abilify Asimtufii injection", "Abilify Discmelt", "Abilify Maintena", "Abilify Maintena Prefilled Syringe injection", "Abilify Mycite",
    "Abilify MyCite Maintenance Kit oral with sensor", "Abilify MyCite Starter Kit oral with sensor", "Abiraterone", "Abiraterone Acetate", "Abiraterone and niraparib",
    "Abiraterone, micronized", "Ablavar", "Ablysinol", "AbobotulinumtoxinA", "Abraxane", "Abreva", "Abrilada", "Abrocitinib", "Abrysvo", "Absorbine Athletes Foot",
    "Absorbine Jr. Antifungal", "Absorica", "Absorica LD", "Abstral", "Abstral Sublingual Tablet", "Vitamin D (Drisdol, Calciferol)", "Amoxicillin (Amoxil, Biomox, Polymox)",
    "Levothyroxine (Synthroid, Euthyrox, Levoxyl, Unithroid)", "Lisinopril (Prinivil, Zestril)", "Ibuprofen (Advil, Motrin)",
    "Amphetamine/dextroamphetamine (Adderall, Adderall XR)", "Amlodipine (Norvasc)", "Albuterol HFA (Ventolin HFA, Proair HFA, Proventil HFA)",
    "Prednisone (Deltasone, Rayos, Prednisone Intensol)", "Gabapentin (Neurontin)", "Benzonatate (Tessalon Perles)", "Alprazolam (Xanax)", "Cyclobenzaprine (Fexmid)",
    "Azithromycin (Zithromax Z-Pak)", "Atorvastatin (Lipitor)", "Cetirizine (Zyrtec)", "Losartan (Cozaar)", "Amoxicillin/clavulanate potassium (Augmentin)", "Cephalexin (Keflex)",
    "Metformin (Riomet)", "Metoprolol succinate ER (Toprol XL)", "Folic acid (Folvite)", "Hydrochlorothiazide (Microzide)", "Sildenafil citrate (Viagra, Revatio)",
    "Trazodone (Desyrel, Oleptro)", "Zolpidem tartrate (Ambien)", "Escitalopram oxalate (Lexapro)", "Clonazepam (Klonopin)", "Methylprednisolone (Medrol)", "Tadalafil (Cialis)",
    "Methocarbamol (Robaxin)", "Fluconazole (Diflucan)", "Sertraline (Zoloft)", "Doxycycline hyclate (Vibramycin, Acticlate, Targadox)", "Furosemide (Lasix)",
    "Fluoxetine (Prozac)", "Metronidazole (Vandazole, Metrogel, Flagyl)", "Freestyle Libre", "Omeprazole (Prilosec)", "FeroSul (ferrous sulfate)",
    "Sulfamethoxazole/trimethoprim (Bactrim)", "Phenobarbital (Luminal, Solfoton)", "Armour Thyroid (desiccated thyroid)", "Bromphen/pseudoephedrine/dextromethorphan (Bromfed DM)",
    "Metoprolol tartrate (Lopressor)", "Meloxicam (Mobic)", "Pantoprazole sodium (Protonix)", "Lisinopril/hydrochlorothiazide (Zestoretic)",
    "Estradiol (Estrace, Climara, Minivelle)", "Famotidine (Pepcid, Pepcid AC, Zantac 360)", "Atorvastatin", "Metformin", "Lisinopril", "Levothyroxine", "Amlodipine", "Metoprolol",
    "Albuterol", "Losartan", "Omeprazole", "Gabapentin", "Sertraline", "Hydrochlorothiazide", "Rosuvastatin", "Dextroamphetamine", "Dextroamphetamine Saccharate", "Amphetamine",
    "Amphetamine Aspartate", "Escitalopram", "Pantoprazole", "Montelukast", "Trazodone", "Simvastatin", "Tamsulosin", "Bupropion", "Fluoxetine", "Acetaminophen; Hydrocodone",
    "Furosemide", "Fluticasone", "Amoxicillin", "Apixaban", "Insulin Glargine", "Meloxicam", "Prednisone", "Duloxetine", "Methylphenidate", "Ibuprofen", "Carvedilol",
    "Potassium Chloride", "Aspirin", "Pravastatin", "Ergocalciferol", "Allopurinol", "Citalopram", "Alprazolam", "Glipizide", "Cetirizine", "Venlafaxine", "Cyclobenzaprine",
    "Hydroxyzine", "Clopidogrel", "Semaglutide", "Famotidine", "Estradiol", "Diclofenac", "Spironolactone", "Hydrochlorothiazide; Lisinopril", "Buspirone", "Tramadol",
    "Empagliflozin", "Clonazepam", "Lamotrigine", "Fluticasone; Salmeterol", "Oxycodone", "Ondansetron", "Cholecalciferol", "Atenolol", "Glimepiride", "Folic Acid", "Zolpidem",
    "Latanoprost", "Doxycycline", "Lisdexamfetamine", "Insulin Lispro", "Clonidine", "Loratadine", "Finasteride", "Dulaglutide", "Hydrochlorothiazide; Losartan", "Insulin Aspart",
    "Propranolol", "Azithromycin", "Ezetimibe", "Ethinyl Estradiol; Norethindrone", "Lorazepam", "Quetiapine", "Budesonide; Formoterol", "Topiramate", "Warfarin", "Sitagliptin",
    "Amitriptyline", "Fenofibrate", "Naproxen", "Rivaroxaban", "Pregabalin", "Paroxetine", "Celecoxib", "Tizanidine", "Sumatriptan", "Amoxicillin; Clavulanate", "Olmesartan",
    "Acetaminophen; Oxycodone", "Ethinyl Estradiol; Norgestimate", "Diltiazem", "Cephalexin", "Triamcinolone", "Alendronate", "Baclofen", "Mirtazapine", "Aripiprazole",
    "Insulin Detemir", "Beclomethasone", "Meclizine", "Pioglitazone", "Benzonatate", "Ferrous Sulfate", "Valsartan", "Nitrofurantoin", "Tiotropium", "Methotrexate", "Acyclovir",
    "Mometasone", "Ethinyl Estradiol; Levonorgestrel", "Liraglutide", "Risperidone", "Cyanocobalamin", "Insulin Human", "Polyethylene Glycol 3350", "Guaifenesin; Dextromethorphan",
    "Levetiracetam", "Omega-3-acid Ethyl Esters", "Desvenlafaxine", "Ethinyl Estradiol; Drospirenone", "Metronidazole", "Dexmethylphenidate", "Dicyclomine", "Ropinirole",
    "Promethazine", "Vilanterol; Fluticasone", "Lansoprazole", "Phentermine", "Isosorbide Mononitrate", "Labetalol", "Oseltamivir", "Methocarbamol", "Guanfacine", "Carisoprodol",
    "Medroxyprogesterone", "Benazepril", "Lidocaine", "Valsartan; Hydrochlorothiazide", "Tretinoin", "Timolol", "Tiagabine", "Brimonidine", "Levocetirizine",
    "Diclofenac Epolamine", "Nifedipine", "Travoprost", "Bimatoprost", "Lurasidone", "Betamethasone", "Loperamide", "Fentanyl", "Terazosin", "Canagliflozin", "Linagliptin",
    "Dexlansoprazole", "Sucralfate", "Nebivolol", "Butalbital; Acetaminophen; Caffeine", "Chlorhexidine", "Doxazosin", "Linezolid", "Dexamethasone", "Hydralazine",
    "Misoprostol", "Anastrozole", "Atomoxetine", "Methimazole", "Indomethacin", "Carbamazepine", "Phenazopyridine", "Etodolac", "Ketorolac", "Ranitidine", "Alfuzosin",
    "Budesonide", "Rifampin", "Enalapril", "Clindamycin", "Desloratadine", "Acetazolamide", "Bacitracin; Neomycin; Polymyxin B", "Penicillin V", "Clotrimazole; Betamethasone",
    "Triamterene; Hydrochlorothiazide", "Dapagliflozin", "Lomefloxacin", "Milnacipran", "Zonisamide", "Carbidopa; Levodopa", "Chlorpromazine", "Diphenoxylate; Atropine",
    "Hydroxyurea", "Divalproex Sodium", "Tizanidine", "Ziprasidone", "Oxybutynin", "Clobetasol", "Estradiol", "Allopurinol", "Erythromycin", "Sulfasalazine", "Minoxidil",
    "Fludrocortisone", "Pramipexole", "Paliperidone", "Dipyridamole", "Olanzapine", "Colesevelam", "Alendronate", "Selegiline", "Prazosin", "Pegfilgrastim", "Cyclosporine",
    "Amitiza (Lubiprostone)", "Cinacalcet", "Bupropion", "Clotrimazole", "Mesalamine", "Finasteride", "Eszopiclone", "Rivastigmine", "Levonorgestrel", "Perphenazine",
    "Nitroglycerin", "Dronabinol", "Varenicline", "Valacyclovir", "Methadone", "Chlorthalidone", "Methylprednisolone", "Tolterodine", "Rifaximin", "Ezetimibe", "Clonidine",
    "Oxycodone", "Cefpodoxime", "Lacosamide", "Olmesartan", "Prednisolone", "Amiloride", "Ticagrelor", "Bicalutamide", "Famciclovir", "Sitagliptin", "Solifenacin", "Amiodarone",
    "Dapsone", "Naloxone", "Azathioprine", "Telmisartan", "Albuterol; Ipratropium", "Ketoconazole", "Methotrexate Sodium", "Nicotine", "Amantadine", "Prochlorperazine",
    "Aripiprazole", "Apixaban", "Vilazodone", "Eplerenone", "Risedronate", "Cabergoline", "Tenofovir", "Avanafil", "Cilostazol", "Darifenacin",
    "Elvitegravir; Cobicistat; Emtricitabine; Tenofovir", "Tetrabenazine", "Desmopressin", "Fluvoxamine", "Lenvatinib", "Empagliflozin", "Glecaprevir; Pibrentasvir",
    "Sacubitril; Valsartan", "Ivabradine", "Riluzole", "Naltrexone", "Benznidazole", "Sofosbuvir; Velpatasvir", "Clobazam", "Osilodrostat", "Patiromer", "Cenobamate",
    "Upadacitinib", "Belantamab Mafodotin", "Capmatinib", "Voclosporin", "Tirzepatide", "Mavacamten", "Tebentafusp", "Abaloparatide", "Metformin 500mg", "Ibuprofen 200mg",
    "Prednisone 20mg"
]
instructions = [
    "Take 1 tablet twice daily", "Take after meals", "Take before bedtime", "Take with a glass of water", "Take on an empty stomach", "Apply to affected area",
    "Take 1 tablet twice daily", "Take once daily", "Take every 8 hours", "Take every 4–6 hours as needed", "Take 2 times a day", "Take at bedtime", "Take in the morning",
    "Take every other day", "Take weekly", "Take with food", "Take after meals", "Take before meals", "Take on an empty stomach", "Take 30 minutes before meals",
    "Take with a full glass of water", "Avoid dairy products when taking this", "Take before bedtime", "Take in the evening", "Take first thing in the morning",
    "Take with evening meal", "Apply to affected area", "Take by mouth", "Inject subcutaneously", "Use rectally", "Instill into eye", "Inhale by mouth", "Use topically",
    "Insert vaginally", "Apply under tongue", "Do not crush or chew", "Avoid alcohol while taking this", "Shake well before use", "Store in refrigerator",
    "Finish all medication unless otherwise directed", "Rinse mouth after use", "Apply a thin layer to affected area", "Do not apply to broken skin",
    "Use only as directed", "Wash hands after application", "For external use only"
]

# Optional: Use a custom font
try:
    font = ImageFont.truetype("arial.ttf", size=18)
except:
    font = ImageFont.load_default()

# Generate prescriptions
for i in range(1, 1000):  # change 101 to 501 for 500 samples
    img = Image.new('RGB', (800, 600), color='white')
    d = ImageDraw.Draw(img)

    d.text((20, 20), f"Dr. {faker.name()}", font=font, fill='black')
    d.text((20, 60), f"Clinic: {faker.company()}", font=font, fill='black')
    d.text((20, 100), f"Patient Name: {faker.name()}", font=font, fill='black')
    d.text((20, 140), f"Age: {random.randint(1, 90)}", font=font, fill='black')
    d.text((20, 180), f"Date: {faker.date()}", font=font, fill='black')

    y = 220
    for _ in range(random.randint(2, 4)):
        med = random.choice(medications)
        instr = random.choice(instructions)
        d.text((40, y), f"{med} - {instr}", font=font, fill='black')
        y += 40

    d.text((20, y + 20), "Signature: ___________________", font=font, fill='black')

    img.save(f"{output_dir}/prescription_{i}.png")



import os
import shutil

folder_name = "typed_prescriptions_input"

# Create the folder if it doesn't exist
os.makedirs(folder_name, exist_ok=True)

# Move all PNG files into the folder
for file in os.listdir():
    if file.endswith(".png"):
        shutil.move(file, os.path.join(folder_name, file))

!zip -r typed_prescriptions_input.zip typed_prescriptions_input/

pip install -q -U google-genai

from google import genai

client = genai.Client(api_key="AIzaSyBHLs5S9rVv3duE8RmJgqyIuqDuM98U9Ds")

response = client.models.generate_content(
    model="gemini-2.0-flash", contents="Explain how AI works in a few words"
)
print(response.text)

from google import genai
from google.genai import types

import PIL.Image

image = PIL.Image.open('/content/prescription_3.png')

client = genai.Client(api_key="AIzaSyBHLs5S9rVv3duE8RmJgqyIuqDuM98U9Ds")
response = client.models.generate_content(
    model="gemini-2.0-flash",
    contents=["What is the medicine name and its dosage", image])

print(response.text)

pip install pymongo

import re

# Extract medicine name and dosage using regex
medicines = []
for match in re.finditer(r"\*\s+\*\*(.*?):\*\*\s*(.+)", response.text):
    name = match.group(1).strip()
    dosage = match.group(2).strip()
    medicines.append({"medicine": name, "dosage": dosage})

print(medicines)

from pymongo import MongoClient

# Paste your connection string here
uri = "mongodb+srv://nsule:bitcamp2025@bitcamp2025.veikbht.mongodb.net/?retryWrites=true&w=majority&appName=Bitcamp2025"

# Connect to Atlas
client = MongoClient(uri)

# Create/select database and collection
db = client["medical_database"]
collection = db["medicines"]

# Insert data
collection.insert_many(medicines)
print("Data inserted successfully!")